### PR TITLE
Updated compiler target architecture

### LINKED ISSUE #37: risc-v toolchain requirement should be documented
When using the risc-v toolchain from debian:
```
ii  gcc-riscv64-unknown-elf                              12.1.0-7+11                                             amd64        GCC cross compiler for Risc-V processors
```
I get the following error when trying to compile some of the test firmware of the repo:
```
riscv64-unknown-elf-gcc -I/home/proppy/src/github.com/efabless/caravel_board/firmware_vex/gpio_test -I../ -I../generated/ -O0 -mabi=ilp32 -march=rv32i -D__vexriscv__ -Wl,-Bstatic,-T,../sections.lds,--strip-debug -ffreestanding -nostdlib -o gpio_test.elf ../crt0_vex.S ../isr.c gpio_test.c
../crt0_vex.S: Assembler messages:
../crt0_vex.S:59: Error: unrecognized opcode `csrw mtvec,a0', extension `zicsr' required
../crt0_vex.S:87: Error: unrecognized opcode `csrw mie,a0', extension `zicsr' required
../irq_vex.h: Assembler messages:
../irq_vex.h:31: Error: unrecognized opcode `csrw 3008,a5', extension `zicsr' required
make: *** [Makefile:30: gpio_test.elf] Error 1
```

It would be nice to document the toolchain requirements and guide the user thru the required setup.

### PR DESCRIPTION
**Pull request by Aidan-McNay**
Modified the compiler architecture flag from `-march=rv32i` to `-march=rv32i_zicsr` to work with modern GCC. This should resolve #37 and #87

### CODE REVIEW

**Review by RTimothyEdwards — APPROVED** [review]
Looks good to me.  @jeffdi , please merge this pull request.

**Review by jeffdi — APPROVED** [review]

**Comment by RTimothyEdwards** [comment]
@Aidan-McNay :  Jeff reports that this is now a problem with the older versions of gcc;  apparently while the _behavior_ of including the "zicsr" package was default, there was no specific architecture name associated with it, so that "-march=rv32i_zicsr" just throws an error.  @jeffdi :  Is this still an issue, or are we dealing with it by insisting on a specific version of gcc?

One solution would be to get the gcc version when running the Makefile recipe and set the architecture version accordingly (although I don't know at what version of gcc-riscv this change was made).  I believe the Makefile is set up so that the value can be passed as an environment variable, so that's a workaround in either case (old Makefile/new gcc or new Makefile/old gcc).  But handling it automatically in the Makefile is the better solution.

**Comment by Aidan-McNay** [comment]
@RTimothyEdwards Ok - apologies for the issues. I can take a look into it and get back soon🙂

**Comment by RTimothyEdwards** [comment]
Actually, looking at the code base, the Makefile compiler options are not set as variables but hard-coded.  So adding something like `RISCV_TYPE ?= rv32i_zicsr` would be a minimal effort to provide a workaround in the case of an incompatible gcc version.

The `RISCV_TYPE` was used in the caravel verification testbenches to accommodate the difference in architecture between the original PicoRV32 and the Vex-RISC and should have been carried over into the caravel_board Makefiles to begin with.

**Comment by RTimothyEdwards** [comment]
@Aidan-McNay :  No need to apologize.  I was just hoping you might be willing to work on a more generally-applicable solution (so that I don't have to!).  If you can, then great, and you have my thanks.

**Comment by jeffdi** [comment]
I created an ARCH variable in the blink Makefile for the
current chipignite firmware.  These need to be propagated
to the rest of the repo.  It might be better to include a master Makefile
with these parameters set.

-- Jeff

**Comment by RTimothyEdwards** [comment]
@jeffdi :  You have changed it to `ARCH=rv132` which is not a compiler target.  It should be `rv32i` (or `rv32i_zicsr`).

**Comment by jeffdi** [comment]
Sorry - I must not have pushed the correction.  Will do now.

-- Jeff

**Comment by jeffdi** [comment]
Thanks.  If you can set that up, I'll look for the PR and push it though.
I'm out of the office next week starting tomorrow, so may not get to review
until I'm back.

-- Jeff

**Comment by Aidan-McNay** [comment]
@jeffdi Just created a PR for this :) (also, not sure about your specific setup, but I'm on an M1 Mac, and I was able to get `riscv64-unknown-elf-gcc` v.12.2.0 from Homebrew)

**Pull request merged**
